### ISSUE TITLE
Binary Release should include arm64

### ISSUE THREAD

**Issue by EpicSkookumScript** [EpicSkookumScript/SkookumScript-Plugin#13]
<a href="https://github.com/error454"><img src="https://avatars3.githubusercontent.com/u/700435?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [error454](https://github.com/error454)**
_Wednesday Oct 23, 2019 at 23:46 GMT_
_Originally opened as https://github.com/SkookumScript/SkookumScript-Plugin/issues/13_

----

The packaging script leverages RunUAT BuildPlugin. This creates a default host project that only builds armv7a for the android platform. Need to figure out how to make it build armv7a and arm64.

**Comment by error454** [comment]
UE4 4.24 build system now builds both armv7 and arm64
