### ISSUE TITLE
Unnecessary p4 stats for Project-Generated-BP on map open

### ISSUE THREAD

**Issue by EpicSkookumScript** [EpicSkookumScript/SkookumScript-Plugin#16]
<a href="https://github.com/error454"><img src="https://avatars3.githubusercontent.com/u/700435?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [error454](https://github.com/error454)**
_Wednesday Nov 06, 2019 at 21:58 GMT_
_Originally opened as https://github.com/SkookumScript/SkookumScript-Plugin/issues/16_

----

**UE4 Version**
4.23.1

**SkookumScript Version**
4.23.1

**Describe the bug**
When opening a map, there seem to be a ton of unnecessary p4 stats in the Project-Generated-BP folder. This should be investigated and brought under control.

**To Reproduce**
Open a map, it can even be a blank map.

**Expected behavior**
p4 stat should only occur if the file in question needs to be replaced and the content is not identical to the existing content.

**Comment by error454** [comment]
Fixed in a95a4fb9e1bdfe346c36603443d2700e2d846f42
