### ISSUE TITLE
Missed UserWidget classes

### ISSUE THREAD

**Issue by MaxStgs** [EpicSkookumScript/SkookumScript-Plugin#19]
UE4 Version: Binary 4.23.0

SkookumScript Version: 4.23.1-0f3

Describe the bug: 
Error: "The UE4 equivalent of class type 'WBP_RootGame' is not known to SkookumScrupt. Maybe it is the class of Blueprint that is not loaded yet?"

1. Create Blueprint from UserWidget with name WBP_RootGame
2. Restart Unreal Engine Editor
3. Click "Play"
4. Open SkookumIDE, after Workbench (REPL)
5. Write WBP_RootGame.static_class
6. Click Ctrl + F4
7. See error

Expected behavior: Name of static class

![изображение](https://user-images.githubusercontent.com/10531103/69565341-98407300-0fd6-11ea-9cbf-1c27f2fb5b64.png)
Code for executing, where is BP_Core_AIC, WBP_RootGame(UserWidget subclass), WBP_Test(UserWidget subclass) - is my own classes
![изображение](https://user-images.githubusercontent.com/10531103/69565409-ba39f580-0fd6-11ea-8c4d-319d44197cd8.png)
Result of executing, where is nil - println(MyClass.static_class) at my own UserWidget classes

Additional context: If compile blueprint in editor, after try to repeat this - then all will fine, but only before restart.

**Comment by error454** [comment]
What is happening here is that UE4 has not loaded the class and therefore Sk doesn't know about it. Once you compile the blueprint, UE4 has then loaded the widget and the class can be resolved. The true solution to this is to make sure that the class has been referenced before you try to access it.

This means the class in question needs to be somewhere in the reference chain of assets. So referenced in your level, your player controller, your game instance etc. This way the class will be loaded when your level loads and will also be included when you package.
