### ISSUE TITLE
More big size of context helper

### ISSUE THREAD

**Issue by MaxStgs** [EpicSkookumScript/SkookumScript-Plugin#20]
I am not like when size of window change size very often(because names of fields so different)

Describe the solution you'd like:
Set more big size, may be 40 symbols minimum

Describe alternatives you've considered: No alternatives
![изображение](https://user-images.githubusercontent.com/10531103/69565837-932ff380-0fd7-11ea-8ebd-5b369a5bc9d7.png)
Example of middle size

![изображение](https://user-images.githubusercontent.com/10531103/69565865-9e831f00-0fd7-11ea-9a92-aead5722e4d3.png)
Example of very little size

**Comment by error454** [comment]
Fixed in https://github.com/EpicSkookumScript/SkookumIDE/commit/31726de84c5c26ee4c795f1af8b3ec97dbb95636
