### ISSUE TITLE
Fix C4996 in SkookumScriptGenerator.cpp

### ISSUE THREAD

**Issue by EpicSkookumScript** [EpicSkookumScript/SkookumScript-Plugin#3]
<a href="https://github.com/error454"><img src="https://avatars3.githubusercontent.com/u/700435?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [error454](https://github.com/error454)**
_Monday Jul 01, 2019 at 16:36 GMT_
_Originally opened as https://github.com/SkookumScript/SkookumScript-Plugin/issues/3_

----

There are several instances of C4996 in `SkookumScriptGenerator` that should be fixed up for future releases.

**Comment by error454** [comment]
Fixed in 5c3d58d15e8ca3d5a40f94435a24b944f8589427
