### ISSUE TITLE
C++ Getting Started Instructions

### ISSUE THREAD

**Issue by EpicSkookumScript** [EpicSkookumScript/SkookumScript-Plugin#5]
<a href="https://github.com/error454"><img src="https://avatars3.githubusercontent.com/u/700435?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [error454](https://github.com/error454)**
_Wednesday Jul 03, 2019 at 02:45 GMT_
_Originally opened as https://github.com/SkookumScript/SkookumScript-Plugin/issues/5_

----

**Is your feature request related to a problem? Please describe.**
It's difficult to get started with sk in a C++ project.

**Describe the solution you'd like**
I'd like clear and complete documentation in the ReadMe.md for new C++ users.

**Comment by error454** [comment]
Fixed in f6b77c3ab22893b6460ee2d1d090756142e1166c
